export const enum Linktype {
  INTACTION = 'INTACTION',

  EXTACTION = 'EXTACTION',

  INTREPORT = 'INTREPORT',

  EXTREPORT = 'EXTREPORT',

  INTWEBLINK = 'INTWEBLINK',

  EXTWEBLINK = 'EXTWEBLINK',
}
