export const enum Prodtype {
  YATIRIM = 'YATIRIM',

  DEGERLIMADEN = 'DEGERLIMADEN',

  YATIRIMFONU = 'YATIRIMFONU',

  SGMK = 'SGMK',

  HISSESENEDI = 'HISSESENEDI',

  BIREYSELKREDI = 'BIREYSELKREDI',

  TICARIKREDI = 'TICARIKREDI',

  KREDIKARTI = 'KREDIKARTI',

  POSTACEKI = 'POSTACEKI',

  HGS = 'HGS',

  FATURA = 'FATURA',

  VADELIMEVDUAT = 'VADELIMEVDUAT',

  VADESIZMEVDUAT = 'VADESIZMEVDUAT',

  WESTERNUNION = 'WESTERNUNION',
}
