import { Moment } from 'moment';
import { IItxcusttype } from 'app/shared/model/itxcusttype.model';
import { IItxaccounttype } from 'app/shared/model/itxaccounttype.model';
import { IItxtxntype } from 'app/shared/model/itxtxntype.model';
import { IItxcurrency } from 'app/shared/model/itxcurrency.model';
import { IAfetljobtype } from 'app/shared/model/afetljobtype.model';
import { Addrtype } from 'app/shared/model/enumerations/addrtype.model';
import { Idtype } from 'app/shared/model/enumerations/idtype.model';
import { Prodtype } from 'app/shared/model/enumerations/prodtype.model';

export interface IItxtxnqueue {
  id?: number;
  etljobstart?: string;
  etljobsessiond?: string;
  createdt?: string;
  updatedt?: string;
  createusr?: number;
  updateusr?: number;
  wfstate?: string;
  wfprocid?: number;
  scsyscustid?: string;
  scname?: string;
  scmidname?: string;
  scsurname?: string;
  scbirthdate?: string;
  sccommtitle?: string;
  scaddresstype?: Addrtype;
  scaddress?: string;
  sccity?: string;
  scnationality?: string;
  scnationalid?: string;
  scidtype?: Idtype;
  scidno?: string;
  scgender?: string;
  saorgid?: number;
  saorgname?: string;
  sasyscode?: string;
  sabranchcode?: string;
  saname?: string;
  rcsyscustid?: string;
  rcname?: string;
  rcmidname?: string;
  rcsurname?: string;
  rcbirthdate?: string;
  rccommtitle?: string;
  rcaddresstype?: Addrtype;
  rcaddress?: string;
  rccity?: string;
  rcnationality?: string;
  rcnationalid?: string;
  rcidtype?: Idtype;
  rcidno?: string;
  rcgender?: string;
  raorgid?: number;
  raorgname?: string;
  rasyscode?: string;
  rabranchcode?: string;
  raname?: string;
  txnchanneltype?: string;
  txnsysid?: string;
  txnprodtype?: Prodtype;
  txnprodname?: string;
  txnamount?: number;
  txndescr?: string;
  txnentitiesupd?: string;
  txnagentorgid?: number;
  txnagentbrachid?: string;
  txnagenttype?: string;
  txnagentaccid?: string;
  txnorderdate?: string;
  txnvaluedate?: string;
  rctype?: IItxcusttype;
  ratype?: IItxaccounttype;
  satype?: IItxaccounttype;
  sctype?: IItxcusttype;
  txntypeid?: IItxtxntype;
  txncurrency?: IItxcurrency;
  etljobtype?: IAfetljobtype;
}

export const defaultValue: Readonly<IItxtxnqueue> = {};
